### ISSUE TITLE
Unable to run mahimahi with the command

### ISSUE THREAD

**Issue by yue2388253** [ccp-project/eval-scripts#1] opened 2018-12-25 03:27 UTC
Is the following command correct?
```
mm-delay 10 mm-link --cbr 48M 48M --uplink-queue="droptail" --downlink-queue="droptail" --uplink-queue-args="packets=160" --downlink-queue-args="packets=160" --log=bbr.log iperf -c $MAHIMAHI_BASE -p 5000 -t 30 -i 1 -Z ccp
```

Firstly, in my machine, mahimahi cannot regconize the parameter "--log=bbr.log". 
Should "--uplink-log" or "--downlink-log" be used instead?

Secondly, should the command " iperf -c $MAHIMAHI_BASE -p 5000 -t 30 -i 1 -Z ccp" be run with "mm-delay" in one command? As far as I understand, this command might be run inside the shell spawned by mahimahi?
I assume that the version of mahimahi I use is different. However, the mahimahi is installed by "ccp-system-setup.sh" and "Makefile", which should have a same result with you.

The environment I use is: Ubuntu 16.10(with kernel 4.13).

**Comment by akshayknarayan** [comment] 2018-12-31 22:25
Hello, thanks for your interest in CCP.

> mahimahi cannot regconize the parameter "--log=bbr.log".
> Should "--uplink-log" or "--downlink-log" be used instead?

We submodule a fork of mahimahi. Please check that there is no issue with your PATH and using the correct mahimahi.

> Secondly, should the command " iperf -c $MAHIMAHI_BASE -p 5000 -t 30 -i 1 -Z ccp" be run with "mm-delay" in one command? As far as I understand, this command might be run inside the shell spawned by mahimahi?

Yes, we want the iperf traffic to go through the emulated mahimahi link.

**Comment by yue2388253** [comment] 2019-01-05 14:18
I followed the guide of README.md(with vagarnt and the Vagrantfile this repo contains). When I tried to `make`, there's a problem when it tried to make mahimahi. That was why I installed mahimahi manully before. The error is as following:

```
cd mahimahi && autoreconf -i
.ibtoolize:    error: AC_CONFIG_MACRO_DIRS([m4]) conflicts with ACLOCAL_AMFLAGS=-I m4
autoreconf: libtoolize failed with exit status: 1
Makefile:24: recipe for target 'mahimahi/configure' failed
make: *** [mahimahi/configure] Error 1
```

**Comment by akshayknarayan** [comment] 2019-01-05 20:13
hm, on a clean vagrant VM and clone of this repo I am unable to reproduce your error:
```
vagrant@ubuntu1710:/ccp$ make
make -C ccp-kernel
[...]
cd mahimahi && autoreconf -i
libtoolize: putting auxiliary files in '.'.
libtoolize: copying file './ltmain.sh'
libtoolize: putting macros in AC_CONFIG_MACRO_DIRS, 'm4'.
libtoolize: copying file 'm4/libtool.m4'
libtoolize: copying file 'm4/ltoptions.m4'
libtoolize: copying file 'm4/ltsugar.m4'
libtoolize: copying file 'm4/ltversion.m4'
libtoolize: copying file 'm4/lt~obsolete.m4'
configure.ac:10: installing './compile'
configure.ac:10: installing './config.guess'
configure.ac:10: installing './config.sub'
configure.ac:6: installing './install-sh'
configure.ac:6: installing './missing'
src/frontend/Makefile.am: installing './depcomp'
cd mahimahi && ./configure
[...]
```

Are you running on windows? It seems there is a known problem with CRLFs. The following link may be helpful: https://stackoverflow.com/questions/47582762/ac-config-macro-dirsbuild-aux-m4-conflicts-with-aclocal-amflags-i-build-aux

Closing, please re-open if issue persists

**Closed as completed by akshayknarayan** 2019-01-05 20:13 UTC
Labels: question

**Comment by yue2388253** [comment] 2019-01-06 14:48
Thanks for your help.
These three following commands help solve this problem.
```
find . -name \*.m4 | xargs dos2unix
find . -name \*.ac | xargs dos2unix
find . -name \*.am | xargs dos2unix
```
